    name: Publish to Verdaccio
     
    # Controls when the action will run.
    # In this case, I'm saying on each release event when it's specifically a new release publish, the types: [published] is required here,
    # since releases could also be updated or deleted, we only want to publish to npm when a new release is created (published).
    on:
      release:
       types: [published]
     
    jobs:
      build:
       runs-on: ubuntu-latest
       steps:
       
       # Publish to Verdaccio
       - run: npm publish --registry http://18.197.210.148:4873/
